spring:
  application:
    name: time
  security:
    user:
      name: ${USERNAME}
      password: ${PASSWORD}
  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
